{
  imports = [
    ./acme.nix
    ./borg.nix
    ./borg-server.nix
    ./builder.nix
    ./chromium.nix
    ./fail2ban.nix
    ./knownHosts.nix
    ./minio.nix
    ./nebula.nix
    ./nextdns.nix
    ./nginx.nix
    ./postgres.nix
    ./sops.nix
    ./tailscale.nix
    ./tlp.nix
    ./vscode.nix
    ./wayland.nix
  ];
}
