{
  imports = [
    ./audiobookshelf.nix
    ./acme.nix
    ./borg.nix
    ./borg-server.nix
    ./builder.nix
    ./chromium.nix
    ./docker-compose
    ./fail2ban.nix
    ./forgejo.nix
    #./grafana.nix
    ./headscale.nix
    ./healthchecks.nix
    ./jellyfin.nix
    ./knownHosts.nix
    ./lldap.nix
    ./minio.nix
    #./nebula.nix
    ./nextdns.nix
    ./nginx.nix
    ./postgres.nix
    ./sops.nix
    ./stirling-pdf.nix
    ./tailscale.nix
    #./tlp.nix
    ./vaultwarden.nix
    #./vscode.nix
    ./wayland.nix
  ];
}
