keys:
  - &admin_infrastructure age1jxa6adhk5azfsefvtw84gk5ge3hxkfygf3sljm3v00s6n8pcdqrq3u92md
  - &admin_workstation age1z9fxldccff0xtmudz4gc44srmf4865vp3r77t3srv5jwmrp8jdcsjdafmt
  - &server_mini-nix age1ggcnz938waklqzssmsahsxh0dm586kcyqxht68p49euyleypecrq2fgr8t
  - &server_infrastructure age1vjhly9gdhewd4d8l6duqh06lvyvrczzkraj8n7r9dym86dehe9vq39uhph
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *admin_infrastructure
      - *admin_workstation
      - *server_mini-nix
      - *server_infrastructure
