#!/usr/bin/env bash
# runs borg list with my default environment

STORAGE_URL=u322294.your-storagebox.de
HOSTNAME=`hostname`
export BORG_REPO="ssh://u322294@$STORAGE_URL:23/./$HOSTNAME"
export BORG_RSH="ssh -i /run/secrets/BORG_PRIVATE_KEY"
export BORG_PASSPHRASE="`sudo cat /run/secrets/BORG_BACKUP_PASSWORD`"

# sudo needed to access the secrets
sudo -E borg list
