keycloak_database_password: ENC[AES256_GCM,data:RMxWCskwLwjgZLyH28IlGrXv08b3rEnR1TpE+tToA7mlmGIG9tUnaXHsUZRTenPe,iv:qkoz7ggBWQa8yMAJgXJyiy9bMJ4yeE7NO8ZZOQyTLlE=,tag:FmPYBu7EG+Zo4UdfoJCnJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xzjwd38z08yra4h6vttp0duqhl3fy65nlcrd000jrcr8hjmzk3qsxgs5fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTkROKzN3ZEtqTkhnSXd1
            UjkrcDhzMEhWK3lsOS8wWWg1USt3OS9OQmhzCjBPVDVuQ2dEZGoyWXowalhBdzQ4
            VStVeC8rV3NvTHBTelpObUFCTWdKTlUKLS0tIFBSREU4UmVNU3FQUXIyV0tBb3hk
            NUNJUGtQb0srRGFpMlJNZC9pRDBCbzgKZ4YdSSqwSMnE/Ro+cCRfHFBNN1tGbBgY
            2VVnMVNJ/ips7qXP2ftCV22Nl7aHk+zsgI7SfQCMKWXKNFsh4lgwtw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1z9fxldccff0xtmudz4gc44srmf4865vp3r77t3srv5jwmrp8jdcsjdafmt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZnNyVTNrNGlUVnNrRXlR
            RC9rbXVTS1kyZGhISVJhVmc4aXpZSk5lbUd3CkRLVjNyTUhkSzJyRkpDZVlaYXJ0
            N3lDNngrSkVIcE1KKzk1ejM0RTRWV1UKLS0tIFAwVDROMUNBOGdNVU5CZlU3STg2
            OFlTSktvKzNqaEtad1NZYVhzZFQrUjgKuSPUGngadx8sX2UT3XSx5EkqnYEVjK3K
            x2cIAY3DbzmdvwQOJP1y79kI1t7p3OdplDY6OP34W61ykYqiHniPjg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ttr8txnr794dxmw6ngp0ygrvs0reajc5js3t4u3kzelkmjgy0qysnq4ufr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWEViZStXSVdsTWx1MFlO
            S0VyVmJzWG44MkpmbFQwYjFTRG4rKy9rcFdjCm1BWFhVSWd6VWlhL3hSV3NQQ2s3
            S0tzK3RVeFo1RWE3b2F3c3JUVEpldW8KLS0tIFlwemgvSDZXMk9FeVd5WW8zYnl1
            eEttUnE2RFNTMTBVRVdka0RiM2Z3UjAKg1HEz2Yua9W3IYo4Eb0ddS1bTe1uYtnV
            Q+hKpoivRDR9atBSqhcefUm8UB+Ilu8Qlbut0x+u8B4f8/J1lBn4HQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-26T04:04:46Z"
    mac: ENC[AES256_GCM,data:NvuLe2ahVXEF60WsrKvFWSQ4dDjnmoBoFUw2gvFEn8UyRjo1Zvx1YuE47sQ0tTvhZw5AdL39yNSBQHd1EMgt0Bu5TDYj6GLGK4Sg77t/3vN6ny9QNE6I3EsN1S0KpbxyZHgKjILg0/1Z5Hq98RZQmLCrhJnGclAFH+rIUYsKTqw=,iv:MeBc3bFcNa3rjNIfH3+XF+hyrii97c+atGz8ivCoKSY=,tag:ghxagIHa731QDdFN/d36LQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
