keycloak_database_password: ENC[AES256_GCM,data:RMxWCskwLwjgZLyH28IlGrXv08b3rEnR1TpE+tToA7mlmGIG9tUnaXHsUZRTenPe,iv:qkoz7ggBWQa8yMAJgXJyiy9bMJ4yeE7NO8ZZOQyTLlE=,tag:FmPYBu7EG+Zo4UdfoJCnJA==,type:str]
LLDAP_JWT_SECRET: ENC[AES256_GCM,data:7AH9IAWdFlcR7Ywtwy8CGSn6oVW0vHCGefwg0KFafMfFCsX1idKlM5aAMoahDSzB4cCABkA3zNemDETvs7/W5HeHdwSDpGl3ftyy7ZCL+8FsknJZj4v+58ARki1mP59gmK7wjQojK6v06/rMKnAhcJ5/2kmVkZkxo/DyiMUXggM=,iv:5AsbRhjbBgMtsi7xRwF0kMxGv+p+dqzdpRnDGm5bD5U=,tag:QWTAdq7togEieSMXbBnwjA==,type:str]
LLDAP_LDAP_BASE_DN: ENC[AES256_GCM,data:FT1PW9Sk8tK/9V5TPg==,iv:in+qEJLCNY+vMzqXql0xSWOVBOCS3oDA3QaSEVLGGec=,tag:xrAu9K7p03FF3zw8+FANpg==,type:str]
LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:5Ea5pHWNPOHdLJhQOLmYzuPxnSmFHunf0Ov19pp9dl2CUkP0S9sVyXAYXeFdXXjgdnh6QqJFkKThsQjNOxIOPth/prQD7r5I1q8ADqyXm57qTxrTDSU4GgzDQfhfH/56I3Tf2Y4S4ae8iz68ojI/jYGEOsxWI/iAPF/uKKBdyMo=,iv:jYaoMg9VCU3S/aUZwEHSaIO4C+14Y5WdYfN/Yql7Yig=,tag:5P85bX7tfWB1L0pudH+UiA==,type:str]
FORGEJO_DATABASE_PASSWORD: ENC[AES256_GCM,data:Qpl3r265yQ19CGU05yX0fau3NtGewNeAoRMCFC6cEQwOmqjS9sRO9r3jXUQVmevDyW4b2HyvxJtExzjj+kV5x8Pd28VZoNnhYPzLh9qJEa+H2bmzSfd8ty3B85bA97MjD1Z6O08k0++E0T4oCN4EeYGQBQW4w7qSLdKHpQ==,iv:LD+0M/oMomiiWAZR46Gfm8NPdjr9oy3KmROWF9kqFRs=,tag:NVoxkVApjuwb+sEvDFTMPA==,type:str]
FORGEJO_SECRET_KEY: ENC[AES256_GCM,data:EQ==,iv:KJUygfhBFGEdVSjmP+5+NzyPrRAwdPKJu2eBtEJLVO4=,tag:Cw3bmyJTA99cqDBcK/0Xnw==,type:str]
FORGEJO_INTERNAL_TOKEN: ENC[AES256_GCM,data:hLyN3w+kb248OBUouHWBQmp+SpdqBixmaVpyJvC6VsPa2KVCG/K8xfNp11yK86vMQX+dLUio2CeX3S3TwgiqFRuwNtVzCSUFcAOplAlf6T/imAJdtALJ3vm67MeLge05HaEYpv4pdlLh,iv:P2PT9ihF3YDKF/zxvDE3gxB/XYIkGr7R5Fer31SAek8=,tag:u70RlTSNlshTFXEnI3zdEQ==,type:str]
FORGEJO_OAUTH_JWT_SECRET: ENC[AES256_GCM,data:16DcxOPOO4kYmCXgX2xEb/CZWPyGqEzwck+vQfHhCWTcrOYe4cejPxEdHg==,iv:iIZDffiHO/kp9soWXQ2Vdbw9yVGoilzGLk69SeAYIrk=,tag:vH5CO7sx9kYuMSq2xPvxbQ==,type:str]
FORGEJO_LFS_JWT_SECRET: ENC[AES256_GCM,data:8DscCS8Le4CZ3KypduWZWthKb3LbpvLZvdxEdaprDnLLAmkwhUu2pjcmOw==,iv:LYVTEET+L7+EjWGesCzXRMzVp3GQGsvkh2JdktPqLRk=,tag:asCYx+2JiKpoXzjqVHO/eA==,type:str]
nextcloud:
    admin_password: ENC[AES256_GCM,data:KXWrIyXvtZLmI+e0XoMdCP8eCJGl3L9w,iv:0hlEPgu/wUrc1Xrg84le3PkaP1LFxe6YcSptN7RpvCI=,tag:UAmAnlZBSQQb9AKZlT0H6A==,type:str]
    db_password: ENC[AES256_GCM,data:/xAgU8hpjUabiWTwRLOIv57WiMbOUD9IlVfdXu/NogYWPseUi9pxoOK1VEPllu55vRrms0bgRwp7D8I8m6nvCA==,iv:DidfTzhMp+ciaBsA5mtw0ezVGrApmLKQXIQRENRt80U=,tag:5Qh+6JwOw4G09PRfg9bI/g==,type:str]
onlyoffice:
    secret: ENC[AES256_GCM,data:ZqeiNSl4oKCH3uH0nS5GhAbLIw1lj6BJx2OqA9XeD7aYI7SH0udFJb4tmdTC0UxG6pQeYISL3hzXCCk4ZI0fSrAUf6gk4H3HP++ng7S10/6j13SkVUFYveoPwDlRseIOItdyBDMMZjH/AQ/gy2Syx+Oqcsuxa5OESh/gVNX9qu0=,iv:4qG3FmNSLMeaerD9qAM4r6mjpm1tYvthzI4khReaU7Y=,tag:x63uKTOVA5NcoWapAcIgVw==,type:str]
    db_password: ENC[AES256_GCM,data:kAscJso1+h3Qewxi/Oy8OvOdtQGWbaQSRTx/IigUckf0Y1jC6rADaJ0PJQFgtObaJLS1+rNTfdZag76YzMAlXw==,iv:Yo+88YfO610aj/q6gsNwXCdf7FM/cL0h3EyndQHPBX8=,tag:by9+nYqIPUC6hllsZuCNLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xzjwd38z08yra4h6vttp0duqhl3fy65nlcrd000jrcr8hjmzk3qsxgs5fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBseUZRMUI3OVVsbE85SkNr
            N21QeWhWdThKalYyMmNGSFdSYnJyYTRaYlJZCkMxZ2dOeExRM0pGbTlIamQ2RFpT
            WGtMMVFxWXc1QU5WM3lFRnRsbGthL28KLS0tIEJVbXZobWJMdWt1UWpCamk4S2Uy
            aG12YloyZVMrQUs1eDdPYnpjUEpOZFkK6TO7inwWG0BsFBgOeze7Zu4Kt+kxTXfQ
            /V9CqkPxhgScRjOo+T15QYRcmQMF/CIH0W/Pp/EznK/DdxUTdmQL9Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1z9fxldccff0xtmudz4gc44srmf4865vp3r77t3srv5jwmrp8jdcsjdafmt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSElvZWtIMXRRQjUyOUdr
            VXFlU3o2TEpSMjNQeTREOVo1ZnRITlQ1K3pNClpiS3R5NUdQY3ZlWlhuR2pWdTZ0
            aWQ1UytmdDIrSGUyWnJ0MjA5WkQ3Y0kKLS0tIEJCSVNhWkx3OWVxUFQ3U3BaQzZE
            dDlrSTFZQk1pOUVJMzFXZzFyaWVUVDAKlywNlDt8prZXXOzkMDUU7f8TBWD983m7
            3WCPFHBZcExR4zMbhYZMR0LoB50ekIldhWGNfEXDtLghWyIzFe1MVg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q0dsdexnmmqxej4emyn9sg6l7y4lh80hhd5958q4e0x6fd8dks0s4fv8nx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzR2FWeU5mVUF6UHYyeVZB
            WEppT2ZNVWxHTWpvNGg0UE1yNG1Hd25vMjJJClMrRU5jZGdYRzZXTFUwdURrYWJl
            YnJkUmV0RElyT2VOczRtS3c0RnI4Q0kKLS0tIDZpY0Y1dDZTWlVWaUhRVEVmalRL
            YURhazVRL01RUDZKWDdic29OakhqMncKeU6suXemwrJX9CNN8YeEIMdudwEfc+Tq
            dsf3QhD5kfHQZ06LUuTV7mDJCaSLtUXNJzgAzQzWuwYgTQDVru8uvQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ttr8txnr794dxmw6ngp0ygrvs0reajc5js3t4u3kzelkmjgy0qysnq4ufr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQ1pkQ1hZT1h2RW03Sm1K
            OGhnOFM3U3lTa2dvQ3gwWVphNjR4VFM3b0g4CkdNNHJlZ001RnpJTk9weTFHcENI
            Qy9hWWVsVTROcGt2VFNRaGxRcTRrV2cKLS0tICs5SjBvM0lxZFFFN29vMFdNbHJJ
            a0lNNzRFeDRTY1Q0clBLNWFlbHpDNUkKw6H09JbybnEdqiWPPLdiGeivzxX7Rywy
            zmLXBvIq3sV0uHALmDjYsDG7x8pg09OgPEHD7GWhHdCiTvCbcbdllQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-17T04:43:27Z"
    mac: ENC[AES256_GCM,data:bue/IBHuWa09RIEs+FVMfSHBHRalEM1lrwKrYsH7m3qys5N+854VzAoegcGH1xZIFjht221xHdC2lXJCypdKDizp/NV6zzGAcyszMG+9Ew/akqq7BytAKojqB6ODdB4ZjWUEkgDf3ZJ4uwDyYcJTW4LAKuZGXpZdLwu7wXZ9kJ8=,iv:OWYqejKr1vdSzhXMCl7FugxZ/kn7JG5v0x4BbzwXqzM=,tag:4FsRH58tGqS27ECHvddMcQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
