keycloak_database_password: ENC[AES256_GCM,data:RMxWCskwLwjgZLyH28IlGrXv08b3rEnR1TpE+tToA7mlmGIG9tUnaXHsUZRTenPe,iv:qkoz7ggBWQa8yMAJgXJyiy9bMJ4yeE7NO8ZZOQyTLlE=,tag:FmPYBu7EG+Zo4UdfoJCnJA==,type:str]
LLDAP_JWT_SECRET: ENC[AES256_GCM,data:7AH9IAWdFlcR7Ywtwy8CGSn6oVW0vHCGefwg0KFafMfFCsX1idKlM5aAMoahDSzB4cCABkA3zNemDETvs7/W5HeHdwSDpGl3ftyy7ZCL+8FsknJZj4v+58ARki1mP59gmK7wjQojK6v06/rMKnAhcJ5/2kmVkZkxo/DyiMUXggM=,iv:5AsbRhjbBgMtsi7xRwF0kMxGv+p+dqzdpRnDGm5bD5U=,tag:QWTAdq7togEieSMXbBnwjA==,type:str]
LLDAP_LDAP_BASE_DN: ENC[AES256_GCM,data:FT1PW9Sk8tK/9V5TPg==,iv:in+qEJLCNY+vMzqXql0xSWOVBOCS3oDA3QaSEVLGGec=,tag:xrAu9K7p03FF3zw8+FANpg==,type:str]
LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:5Ea5pHWNPOHdLJhQOLmYzuPxnSmFHunf0Ov19pp9dl2CUkP0S9sVyXAYXeFdXXjgdnh6QqJFkKThsQjNOxIOPth/prQD7r5I1q8ADqyXm57qTxrTDSU4GgzDQfhfH/56I3Tf2Y4S4ae8iz68ojI/jYGEOsxWI/iAPF/uKKBdyMo=,iv:jYaoMg9VCU3S/aUZwEHSaIO4C+14Y5WdYfN/Yql7Yig=,tag:5P85bX7tfWB1L0pudH+UiA==,type:str]
FORGEJO_DATABASE_PASSWORD: ENC[AES256_GCM,data:Qpl3r265yQ19CGU05yX0fau3NtGewNeAoRMCFC6cEQwOmqjS9sRO9r3jXUQVmevDyW4b2HyvxJtExzjj+kV5x8Pd28VZoNnhYPzLh9qJEa+H2bmzSfd8ty3B85bA97MjD1Z6O08k0++E0T4oCN4EeYGQBQW4w7qSLdKHpQ==,iv:LD+0M/oMomiiWAZR46Gfm8NPdjr9oy3KmROWF9kqFRs=,tag:NVoxkVApjuwb+sEvDFTMPA==,type:str]
FORGEJO_SECRET_KEY: ENC[AES256_GCM,data:EQ==,iv:KJUygfhBFGEdVSjmP+5+NzyPrRAwdPKJu2eBtEJLVO4=,tag:Cw3bmyJTA99cqDBcK/0Xnw==,type:str]
FORGEJO_INTERNAL_TOKEN: ENC[AES256_GCM,data:hLyN3w+kb248OBUouHWBQmp+SpdqBixmaVpyJvC6VsPa2KVCG/K8xfNp11yK86vMQX+dLUio2CeX3S3TwgiqFRuwNtVzCSUFcAOplAlf6T/imAJdtALJ3vm67MeLge05HaEYpv4pdlLh,iv:P2PT9ihF3YDKF/zxvDE3gxB/XYIkGr7R5Fer31SAek8=,tag:u70RlTSNlshTFXEnI3zdEQ==,type:str]
FORGEJO_OAUTH_JWT_SECRET: ENC[AES256_GCM,data:16DcxOPOO4kYmCXgX2xEb/CZWPyGqEzwck+vQfHhCWTcrOYe4cejPxEdHg==,iv:iIZDffiHO/kp9soWXQ2Vdbw9yVGoilzGLk69SeAYIrk=,tag:vH5CO7sx9kYuMSq2xPvxbQ==,type:str]
FORGEJO_LFS_JWT_SECRET: ENC[AES256_GCM,data:8DscCS8Le4CZ3KypduWZWthKb3LbpvLZvdxEdaprDnLLAmkwhUu2pjcmOw==,iv:LYVTEET+L7+EjWGesCzXRMzVp3GQGsvkh2JdktPqLRk=,tag:asCYx+2JiKpoXzjqVHO/eA==,type:str]
NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:AeEpGADjkEy9LEwAMmkDism4lP3Zm6py,iv:ln1vAJVPGHApWbp/CxQtIeHgEL2n8n5+9B4ix2gYR3I=,tag:9usHEMVD11/VOjsrHb4jKA==,type:str]
NEXTCLOUD_DB_PASSWORD: ENC[AES256_GCM,data:5qQjCBxD0Z4rZeK28RzyELz6VvDsgWaUjn8T8Uy8hYpn1O8P86GAg+0R1e7e7DXuYabZXnw8mV7EYIIsE2YU9A==,iv:c/4jf8jh7pYsdEwvgyGu0lddYrDcIIb4GlXLfgtHf78=,tag:Pqaq/Z8ksVU2e8iwLSGhag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xzjwd38z08yra4h6vttp0duqhl3fy65nlcrd000jrcr8hjmzk3qsxgs5fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTkROKzN3ZEtqTkhnSXd1
            UjkrcDhzMEhWK3lsOS8wWWg1USt3OS9OQmhzCjBPVDVuQ2dEZGoyWXowalhBdzQ4
            VStVeC8rV3NvTHBTelpObUFCTWdKTlUKLS0tIFBSREU4UmVNU3FQUXIyV0tBb3hk
            NUNJUGtQb0srRGFpMlJNZC9pRDBCbzgKZ4YdSSqwSMnE/Ro+cCRfHFBNN1tGbBgY
            2VVnMVNJ/ips7qXP2ftCV22Nl7aHk+zsgI7SfQCMKWXKNFsh4lgwtw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1z9fxldccff0xtmudz4gc44srmf4865vp3r77t3srv5jwmrp8jdcsjdafmt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZnNyVTNrNGlUVnNrRXlR
            RC9rbXVTS1kyZGhISVJhVmc4aXpZSk5lbUd3CkRLVjNyTUhkSzJyRkpDZVlaYXJ0
            N3lDNngrSkVIcE1KKzk1ejM0RTRWV1UKLS0tIFAwVDROMUNBOGdNVU5CZlU3STg2
            OFlTSktvKzNqaEtad1NZYVhzZFQrUjgKuSPUGngadx8sX2UT3XSx5EkqnYEVjK3K
            x2cIAY3DbzmdvwQOJP1y79kI1t7p3OdplDY6OP34W61ykYqiHniPjg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ttr8txnr794dxmw6ngp0ygrvs0reajc5js3t4u3kzelkmjgy0qysnq4ufr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWEViZStXSVdsTWx1MFlO
            S0VyVmJzWG44MkpmbFQwYjFTRG4rKy9rcFdjCm1BWFhVSWd6VWlhL3hSV3NQQ2s3
            S0tzK3RVeFo1RWE3b2F3c3JUVEpldW8KLS0tIFlwemgvSDZXMk9FeVd5WW8zYnl1
            eEttUnE2RFNTMTBVRVdka0RiM2Z3UjAKg1HEz2Yua9W3IYo4Eb0ddS1bTe1uYtnV
            Q+hKpoivRDR9atBSqhcefUm8UB+Ilu8Qlbut0x+u8B4f8/J1lBn4HQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-07T13:48:33Z"
    mac: ENC[AES256_GCM,data:TewybuK+XTGlqVC4ubUznu0Mprz6o/Ei0d4sGyN5VlaY/otMRoTc+trjq8EKt2N5nDMn1UIPVTA/CgRP0ScmbfYcqJ3/dZ70k0gbMor5RttGNGD+csTjKTy8pxM6JS0/eYNvUk3nSWUnL1epYh0kOhVhgBGguK5wuVgDQopz0IY=,iv:CJccJAUhSPhlGrKRsbmNNz1Jq0jREnXYTJl0ZEWpyXA=,tag:02NHYYU+j+7ZovmJT1+xEQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
