keycloak:
    database_password: ENC[AES256_GCM,data:kpfkKMh1Pt82lB10KgxGfdn6QkxJm+8RmIS684Kh8rOf1nWcyDw7Ym/QAlsQBAXe,iv:VJTmVh5CcYtzmDiLXWkrylCbl7HXN43OGaCjz22qT2U=,tag:6uUYC01xjTzejaEEP/vTRw==,type:str]
lldap:
    jwt_secret: ENC[AES256_GCM,data:t+vhZuWzlbJCWrcNcBKmuHyzYDSncjrZ8mqK+v3WY2Qa80AdQ6leBpoXVuStak5R6meX9MiLXwbP4q3M7ItmbCwxtzbTiIkOdhuuczyITcniAnApnhYEmkzdp9sROpaPBAIlBRsupV1eA83GcIvaD8TFeqn1L22iWpk93vn5l5U=,iv:5NVQxdWfXz7Yl/8qDWiiLi8wS28jcgz7clWZ3JHfMAs=,tag:jJSlKhYf0fotxGS/HJ1tZw==,type:str]
    ldap_user_pass: ENC[AES256_GCM,data:+JS2vwA3pyr11a3TFueclMbXrGvfkUIGCpbV3RM2fB3Ac/HFjxJn9xX2Ez52l5e0ysCBggatU/Kbv3VXbkcOK0PXd9O3R4DIyrDi0ZfPU8EpSHxfRGZQPD7QnXQMkiFZyZnhGyQhepr/tlqA/5sb6CWgRdC7p0nQcbFq19nwOko=,iv:OUZOgPoWSGcvYVx6nDwfwJS92GU53ZtWDNVQIwB5Pyk=,tag:OMKZqDDeV/fkTXpkrCd6tg==,type:str]
forgejo:
    database_password: ENC[AES256_GCM,data:NA7LM0mndbQpgeXSPp27VrgLoJdP6S38DDPJ8hxEFzPDE7Z6O9UkPNMWuyUBSYgkyBpPnzdElyYZ/mpJiajS59RXnRfhbCu/EFsmFgci7ahtGrIr93+AXni98AeMrM0vIYRvN90UGC8Z8oIvPcpYn/wgk7nSyvDgsIU1xA==,iv:uS9nXL29W+uBe8HWinSQVht2aMbL6K+V4leHP+VvZ2A=,tag:tkvuR9hUOMx5shuxbFKdqA==,type:str]
    secret_key: ENC[AES256_GCM,data:Nw==,iv:3wDYNk1gF5zICwTXHB/tNppG5HufgfMOTp2ihtiJ2z0=,tag:dt7klRFU1vUP/ujAlhNsug==,type:str]
    internal_token: ENC[AES256_GCM,data:tySUs9iGaQIE+XDJJLQoYneydejgp1jhnmMGDo/dcKoS768DL7kYRejzxEnLydFAYCcQR2YKwnuKOn+nAjMaEUWDCoRH+BmNnlc+18rs6pmmTHBqNlbcYeC7YoIWc6LNNgUUu6WAdnO3,iv:Fg2tjON/7dugYvOWS2/YV4lDrORf5+tvn+IPwFmdI84=,tag:AqNMS/72B38GahLxBPPaeQ==,type:str]
    oauth_jwt_secret: ENC[AES256_GCM,data:pv7TUKWCQfa84sLk1Fh2IYqq8gjqi+fEPZrD4cywFaI27HYaCBduGM81RA==,iv:kfGL7J5ljVx2oDAMDFjCuxsEKU6dyuKatadl3/I9ujc=,tag:GpAgKvI2kpXvnDjyPmYdfA==,type:str]
    lfs_jwt_secret: ENC[AES256_GCM,data:ca6pxrof/WCg82k3I3nPxmtxxDHAIaRFwTXpDr9HDfo9xoTHUu8BD2wPTQ==,iv:CKyJFHDOtThuXxQgKDFHI3ayeb5tYsIVFK1icFNgLPg=,tag:Fcz0EVMquY3VLo8kjJ5wUg==,type:str]
nextcloud:
    admin_password: ENC[AES256_GCM,data:KXWrIyXvtZLmI+e0XoMdCP8eCJGl3L9w,iv:0hlEPgu/wUrc1Xrg84le3PkaP1LFxe6YcSptN7RpvCI=,tag:UAmAnlZBSQQb9AKZlT0H6A==,type:str]
    db_password: ENC[AES256_GCM,data:/xAgU8hpjUabiWTwRLOIv57WiMbOUD9IlVfdXu/NogYWPseUi9pxoOK1VEPllu55vRrms0bgRwp7D8I8m6nvCA==,iv:DidfTzhMp+ciaBsA5mtw0ezVGrApmLKQXIQRENRt80U=,tag:5Qh+6JwOw4G09PRfg9bI/g==,type:str]
onlyoffice:
    secret: ENC[AES256_GCM,data:ZqeiNSl4oKCH3uH0nS5GhAbLIw1lj6BJx2OqA9XeD7aYI7SH0udFJb4tmdTC0UxG6pQeYISL3hzXCCk4ZI0fSrAUf6gk4H3HP++ng7S10/6j13SkVUFYveoPwDlRseIOItdyBDMMZjH/AQ/gy2Syx+Oqcsuxa5OESh/gVNX9qu0=,iv:4qG3FmNSLMeaerD9qAM4r6mjpm1tYvthzI4khReaU7Y=,tag:x63uKTOVA5NcoWapAcIgVw==,type:str]
    db_password: ENC[AES256_GCM,data:kAscJso1+h3Qewxi/Oy8OvOdtQGWbaQSRTx/IigUckf0Y1jC6rADaJ0PJQFgtObaJLS1+rNTfdZag76YzMAlXw==,iv:Yo+88YfO610aj/q6gsNwXCdf7FM/cL0h3EyndQHPBX8=,tag:by9+nYqIPUC6hllsZuCNLA==,type:str]
invidious:
    db_password: ENC[AES256_GCM,data:fs5kt8NIOONezIwsG9Y8Hb8T0jm7bJpiq7+IAUZSaTydat0x1EkGnDYhOKYauNZXvNs22uNbHoCtzrLc8mobHg==,iv:VPWKghEgkMtMy+EV7nE/8wvC0tAWDcPTgJ57hOLFtMY=,tag:HUy1FxlerXxJC70P0B9qVw==,type:str]
    settings.json: ENC[AES256_GCM,data:9S/N3jD72BEVi3h1pqKgdrlY4P+MWuEc0+e3eXSeBo9yecb36tJ0z/PByBlrtu/Q+4Xb17Z/A8oQBvZ63UXGQTRNoy65vMbHxJ5IPl4bTPh2oorYg2pwLKmBLwAXzIN9dF5ssPS3sdreuFUJa2KKMyfs3Nr8grgEO9YqnP0hWS6gSP+LNUdiVWkJPl6JnUyepH9oPJAR2plyOuFOkO1h6gsc/B+CT4ncCW2UEQuRc3QRMlV52G3mOVFoUKshWddYd944zhhwl/jFnKLjL3o54hmkYeYNhBEz9yflqrkuKoKYhkj2QsK6jQkkkYuxQIAg8uiBhKIALl3ukj1WX0Qu1HYhbVYZDdw1JclK8YxwSDMU1NuER9JFXwj13FmulSAf8jH4BpWp624wFpqJudZIMdQgEFgU223m8JYuUk+Em0JjVGdTmA==,iv:69vvNufUksYGM6FLu5n1kyxWek+DMmK+8sBu3otvC5A=,tag:QoTtt6FRX5Lzs+bvuaiCqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xzjwd38z08yra4h6vttp0duqhl3fy65nlcrd000jrcr8hjmzk3qsxgs5fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBseUZRMUI3OVVsbE85SkNr
            N21QeWhWdThKalYyMmNGSFdSYnJyYTRaYlJZCkMxZ2dOeExRM0pGbTlIamQ2RFpT
            WGtMMVFxWXc1QU5WM3lFRnRsbGthL28KLS0tIEJVbXZobWJMdWt1UWpCamk4S2Uy
            aG12YloyZVMrQUs1eDdPYnpjUEpOZFkK6TO7inwWG0BsFBgOeze7Zu4Kt+kxTXfQ
            /V9CqkPxhgScRjOo+T15QYRcmQMF/CIH0W/Pp/EznK/DdxUTdmQL9Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1z9fxldccff0xtmudz4gc44srmf4865vp3r77t3srv5jwmrp8jdcsjdafmt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSElvZWtIMXRRQjUyOUdr
            VXFlU3o2TEpSMjNQeTREOVo1ZnRITlQ1K3pNClpiS3R5NUdQY3ZlWlhuR2pWdTZ0
            aWQ1UytmdDIrSGUyWnJ0MjA5WkQ3Y0kKLS0tIEJCSVNhWkx3OWVxUFQ3U3BaQzZE
            dDlrSTFZQk1pOUVJMzFXZzFyaWVUVDAKlywNlDt8prZXXOzkMDUU7f8TBWD983m7
            3WCPFHBZcExR4zMbhYZMR0LoB50ekIldhWGNfEXDtLghWyIzFe1MVg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q0dsdexnmmqxej4emyn9sg6l7y4lh80hhd5958q4e0x6fd8dks0s4fv8nx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzR2FWeU5mVUF6UHYyeVZB
            WEppT2ZNVWxHTWpvNGg0UE1yNG1Hd25vMjJJClMrRU5jZGdYRzZXTFUwdURrYWJl
            YnJkUmV0RElyT2VOczRtS3c0RnI4Q0kKLS0tIDZpY0Y1dDZTWlVWaUhRVEVmalRL
            YURhazVRL01RUDZKWDdic29OakhqMncKeU6suXemwrJX9CNN8YeEIMdudwEfc+Tq
            dsf3QhD5kfHQZ06LUuTV7mDJCaSLtUXNJzgAzQzWuwYgTQDVru8uvQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ttr8txnr794dxmw6ngp0ygrvs0reajc5js3t4u3kzelkmjgy0qysnq4ufr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQ1pkQ1hZT1h2RW03Sm1K
            OGhnOFM3U3lTa2dvQ3gwWVphNjR4VFM3b0g4CkdNNHJlZ001RnpJTk9weTFHcENI
            Qy9hWWVsVTROcGt2VFNRaGxRcTRrV2cKLS0tICs5SjBvM0lxZFFFN29vMFdNbHJJ
            a0lNNzRFeDRTY1Q0clBLNWFlbHpDNUkKw6H09JbybnEdqiWPPLdiGeivzxX7Rywy
            zmLXBvIq3sV0uHALmDjYsDG7x8pg09OgPEHD7GWhHdCiTvCbcbdllQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-24T07:07:13Z"
    mac: ENC[AES256_GCM,data:u4d57h+WWj2RfaRnQbxKB0PJyaqX9RrK/e8p8MjEVmaYluQIUhmnFmIjed8Sz8eaf3YcuxcQTeLqEWRwkDFrTGbjWJM3iJRkZbLYaUieZiFHDDJI2Nh2LYYe88lMRLsJIHstq4//bEkTrUD7Q7pS3rgZo5r1+8q0dW6Ya99T66E=,iv:gUQcTShsbL+NoZPkAocQmYK3Z0DVQUGJdb5onFaEk1k=,tag:moWZ+oWafU52zGMgFmOJtg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
