derp_path: ENC[AES256_GCM,data:4QYcWk81s48LKGhsmftGAoaEyOlmrjzDL/sKiyOVHNmgLeAtKdcLt9/eoWr4+9uxe7AFhV6dGOGUFdxlzIbGacr4MWq97LgsitJql6aP9fArg4BYRMMrI2BFFopOlOzsf65bYqGzaplgfEvLATxTcQYbJo6feLeq3iLt62CDH0aCm26lYiZqGWldzCOTC+JWsoRYqpVFhJ0Q5ssImpwxEcSqQf0L0zRpWIW4FJznofUwvRx8GlhzrnmtP5M4RvlPtHTJabP7PuLH/roujWnT281E/qM6qk7NB6D9bO+vykTilu+NRLn2l/oWliQ9anqRE2RUvGmXGP4YWGh7JviBprw6dnAQAOyuSvMHYmTrZA7HPXCRryFyxlf5TtqpCm7Ov/mUAA+mtvhCVEm//hEeIZj1sRxhjdppjpJYP83MnU0QYo8eepdm9ovADBrXK/0bDjaJw3mNkPzFJ3LUtUIjxaFYdeI9qA41vaj124mWvcDKKEtGAo8nlrbZ2xzXsaw9/LuMrVZe,iv:kFC+mk3h7r+rJZu8fBCzosHLiiZdkIjuvX7PtK6S4J4=,tag:gKy80WsOvOAkQd6l1BrYHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xzjwd38z08yra4h6vttp0duqhl3fy65nlcrd000jrcr8hjmzk3qsxgs5fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMzc1QTBKOElmempvSDlS
            Uk1IU1o2ZWRhRC9vRmgybFZhU3pKUjc5bURjCmJKNUZVUHlPL3RMRmw5VE1EcW1u
            amMyWTc3aSsvdGNsaWR4ZzdwVlpDVUEKLS0tIC9tSnE4Z0JjcTdSWVBCcURIQ3RL
            TldsM0hRTjBaWmpHbFZKeWxpcGd1NUUKOHgkjykN/vahR/VTToEwZRzJWM4SqnZD
            FPTi/X6swACyDG//4njDAH+pc+xtAC+/qOafa9zysONtNkPys6FB3g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1z9fxldccff0xtmudz4gc44srmf4865vp3r77t3srv5jwmrp8jdcsjdafmt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYmVCWkNBWlNOR1NVR2ti
            ZjZId3NkaHFranIwSFRENWo3Q2pIbUUrckJjCjNUTlYzNnppdGsya3FCWEFPNXNU
            UTM0MHloUWo3SVB6YW5tbk1FTkNUV3cKLS0tIFBmSWcxdHRMME9WN01uNmtUQ0ZJ
            NnhUVXBSM0p3dUJPVHpHUTdVemRtaVkKTU3WG1lG622y5Y139GxYSuTzxDbGRqY4
            FTyGVTwWyNgRa5ipOzsEFwbflkWntLTV3GVDgW372uot42EmAYWfVA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ddc9huyw7vfwpu9zj5g0qkmavyxppqlsn6kkynnygaly4f0tjg4splm092
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQzZwb3pHaVV4dEZhb01v
            NDM4NXBkaHVBdC9Da1dSLzBzWkhwbCtoQTJNCk9ibzRmMTJYWkhwQ1p3c015OHp4
            VVpnRm9FaFVzTytuZ1htajZQdHR1V0UKLS0tIFdCQVA0ellVaU5iTDlaVWZUVU1j
            dEFkQXY2b2hldndWT2U5N0VKQ243MTQKyi0XyBfOrllPtLCJfvG4vUAd+HFt8Sqs
            duZ/TEIuw1xhNtUbb069wywZ9vAN77TrwxSXmGcIrMWwjpx0vVNPqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-07T11:57:07Z"
    mac: ENC[AES256_GCM,data:gGgMk/ZMVMsFHX7L3Z9KrYC+90aKj2P/yMKwCWc44JwIxOTYq7jYrMiJ/e/teSwoifXHnYcq65hxSjO/YRNdCcJOlLGr6rpjX+j77sd0A6GjooYKgyALnII8BV1J2tii4W+uS5fnnSj/wBT/esONTDiORXhfYl71BWs1DZhrVP8=,iv:I4Ev8b+w1ZLINUC6E23h8vwBpvyCN9f5jmslvESYkUE=,tag:mA9IujYha4zaht4qGLHH2g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
