derp_path: ENC[AES256_GCM,data:4QYcWk81s48LKGhsmftGAoaEyOlmrjzDL/sKiyOVHNmgLeAtKdcLt9/eoWr4+9uxe7AFhV6dGOGUFdxlzIbGacr4MWq97LgsitJql6aP9fArg4BYRMMrI2BFFopOlOzsf65bYqGzaplgfEvLATxTcQYbJo6feLeq3iLt62CDH0aCm26lYiZqGWldzCOTC+JWsoRYqpVFhJ0Q5ssImpwxEcSqQf0L0zRpWIW4FJznofUwvRx8GlhzrnmtP5M4RvlPtHTJabP7PuLH/roujWnT281E/qM6qk7NB6D9bO+vykTilu+NRLn2l/oWliQ9anqRE2RUvGmXGP4YWGh7JviBprw6dnAQAOyuSvMHYmTrZA7HPXCRryFyxlf5TtqpCm7Ov/mUAA+mtvhCVEm//hEeIZj1sRxhjdppjpJYP83MnU0QYo8eepdm9ovADBrXK/0bDjaJw3mNkPzFJ3LUtUIjxaFYdeI9qA41vaj124mWvcDKKEtGAo8nlrbZ2xzXsaw9/LuMrVZe,iv:kFC+mk3h7r+rJZu8fBCzosHLiiZdkIjuvX7PtK6S4J4=,tag:gKy80WsOvOAkQd6l1BrYHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xzjwd38z08yra4h6vttp0duqhl3fy65nlcrd000jrcr8hjmzk3qsxgs5fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaHdWbmJVTG94TTl5dkZW
            U2xZUERUdjlrVzBqWEFDMDhqTkppUUxOUWtrCjVhcVRHUzB5cmV3THZnbExmS0lU
            L000bU8rNktaY04veGRSRmtVQ3NMek0KLS0tIHcrK3hZb252SHhOdGo3NVJDZFpQ
            OTVlTTZhSWltYjJlSXl1VHZ0QTNLMDAKHJJtF0shuiN804m2XHq2EMtfq+25CyVD
            c3zQu2wZo5qyRh/ZnGt3vSVqluQcRdhHw802YB8HT0JfLjB7gmT2lQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1z9fxldccff0xtmudz4gc44srmf4865vp3r77t3srv5jwmrp8jdcsjdafmt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4aG5PcWQ4MzBzZUJBTXBz
            bnF4NmNIdGIxVENzck50eUE0R3BRby9QL1dFCmhMVFQ0elp0RFBvOGFpc3UxYlBV
            WG9qR21oS1BiTFRka0pWUXdUUjI2UTgKLS0tIHhEMitwRHhTdk40dlZ6SGRYNHdz
            MmNBcjBJZi9ISzg5WkNlVFA2anVrUUEKlID7jwvdIqkUrqoxFf5QHNVzfTgGdOMZ
            NDBGW1QGy4srBNbi46kAqkNw7rvRgEC2nngVCFJCbTysg8jTB8Fjxw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q0dsdexnmmqxej4emyn9sg6l7y4lh80hhd5958q4e0x6fd8dks0s4fv8nx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeE9vb0JEN254dEdpL2tR
            NTJNNmg1Qm5JVmI5L3RMdHZ6VjdVOStDNmt3CnAyaDRDVm8vSVFBUUVJUm1PS3Nv
            NitablhxVit3UTRackpzMWJCZTNtcUUKLS0tIHFCWVpUOE5IMkd3c1RqRzlvTHBG
            U3Azd0IvTmxjYWd0V3V0SWpKNjhLNXMKrkaOhnxtre53Dtt0OddxSMTwt80nop1R
            wHAKzrhZ08+hkAKLYhZdBQRcfBWh/O3BC2IBosnKKDVhwpxvncZ2IQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ddc9huyw7vfwpu9zj5g0qkmavyxppqlsn6kkynnygaly4f0tjg4splm092
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZnhGRmFrMGlCNkZCWURz
            djQzOGcyNnBiMkhpNUdWNnZUeEFzQzdxYWtrCnZ4YTcvd0hITnBZQzE5ZkpQVTdJ
            OWJzL1Ixdk5HTVZCa0VyaGNHMFU3MkUKLS0tIDVYbnQ5Qk9YUlVhbGJ2dk11cXJy
            cU1GZzhpZURCUmRibEQ0YkdrSkRlZDAKY/BNZ1qJ2mNNycbY9QbJDRn47miISQsK
            ucL/ARjsH5SO1T6jUIqSx3/sGCwV8dFxqeWTwn31RI7BLrxUk3dDlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-07T11:57:07Z"
    mac: ENC[AES256_GCM,data:gGgMk/ZMVMsFHX7L3Z9KrYC+90aKj2P/yMKwCWc44JwIxOTYq7jYrMiJ/e/teSwoifXHnYcq65hxSjO/YRNdCcJOlLGr6rpjX+j77sd0A6GjooYKgyALnII8BV1J2tii4W+uS5fnnSj/wBT/esONTDiORXhfYl71BWs1DZhrVP8=,iv:I4Ev8b+w1ZLINUC6E23h8vwBpvyCN9f5jmslvESYkUE=,tag:mA9IujYha4zaht4qGLHH2g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
