derp_path: ENC[AES256_GCM,data:4QYcWk81s48LKGhsmftGAoaEyOlmrjzDL/sKiyOVHNmgLeAtKdcLt9/eoWr4+9uxe7AFhV6dGOGUFdxlzIbGacr4MWq97LgsitJql6aP9fArg4BYRMMrI2BFFopOlOzsf65bYqGzaplgfEvLATxTcQYbJo6feLeq3iLt62CDH0aCm26lYiZqGWldzCOTC+JWsoRYqpVFhJ0Q5ssImpwxEcSqQf0L0zRpWIW4FJznofUwvRx8GlhzrnmtP5M4RvlPtHTJabP7PuLH/roujWnT281E/qM6qk7NB6D9bO+vykTilu+NRLn2l/oWliQ9anqRE2RUvGmXGP4YWGh7JviBprw6dnAQAOyuSvMHYmTrZA7HPXCRryFyxlf5TtqpCm7Ov/mUAA+mtvhCVEm//hEeIZj1sRxhjdppjpJYP83MnU0QYo8eepdm9ovADBrXK/0bDjaJw3mNkPzFJ3LUtUIjxaFYdeI9qA41vaj124mWvcDKKEtGAo8nlrbZ2xzXsaw9/LuMrVZe,iv:kFC+mk3h7r+rJZu8fBCzosHLiiZdkIjuvX7PtK6S4J4=,tag:gKy80WsOvOAkQd6l1BrYHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xzjwd38z08yra4h6vttp0duqhl3fy65nlcrd000jrcr8hjmzk3qsxgs5fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbEVsVXkvbGJSREtDYXdk
            cDJlcDRHYXMrbU9EU0QyMmhvZjhWWWlLaDMwCjV5djVpL2JiSmJTOTNIc3lyQ1dF
            MUVYZWJ4L0ZCOVQyZmtRWDhwNnlUKzQKLS0tIGZGKzQxVDY4QTJqK090ZlFLR1kw
            eEdpUU9VQWp2cXpxelRrbEczSDhWVlkKrE2XvlLIlix1geFUo3whwACUzeGMartd
            3+VLe+TNYgS2qjpxk42rbOyj2jQb0UTUo0gPYoYUso3EU2wjUjCC6g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1z9fxldccff0xtmudz4gc44srmf4865vp3r77t3srv5jwmrp8jdcsjdafmt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMmFOYTZNZTN3OE95UnA4
            VVJJSkZXMDNwcWxnNU9wbWlDOEFBZjJOWWhRCmVyK2htME5LTUVQcXhNeENRRHEz
            b1VvOC9Pb0w2blFVMk91ZU5mV2dYNUkKLS0tIGFiVGJvRmRsRThvMEt5Qzg4T1kz
            Qld4Snl1Zy9EeFRPclI2SzI5ZFJaUDQKfjyPDKF//E2TSOKtEtxnLq4i/hQZAh4S
            6/VBbkMWDFEdjieFcpv97BBLWqnpBt3T2zXQLl008g8WeiKp8i4NhA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q0dsdexnmmqxej4emyn9sg6l7y4lh80hhd5958q4e0x6fd8dks0s4fv8nx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZE9oU1ZjQk96Q2VYVURu
            UjZBcmlZSmY0RlF3ZGxyK0VzNDFYSVhNK0FrCkxFUTlmdlpYam9Cd0prTVc4emoy
            bzZsQmNLcTFWbU9FcjAxU3NvdWJLT0kKLS0tIGt0K1BnTlhPaTlHY3dXR2JUbTNX
            a1pXTXBQY3EzbVo0Z0czV3dhV3g3U1UK0S9DU6QLwKxOZeXPc1h0DHylg4KTaxTD
            1zlBLS0TZmkAbwV11V9lMOhzE5yjWC8RFOpyg4Fl/rEv6S9UsQ8bqQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ewj2skz6kevkzmlc72cc7tw3kx7przgyjlh5upj438u48x05v9eqpgmhuj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TXdUTks0K1pCcjhuVi9P
            cTdlMzVjODluR3RSV3dNVVlac2R6S1gzbm5NClU0OW9zczdMdHJPUmEwVzcvM3lw
            TmFzYUhTbW1aK2xxNFB2eU9xeGxXeUEKLS0tIHZuMndqNjN1YzdGa1BsN1JQbEp2
            WlhEejA3aUNGRDZtcWgyNzFyMmE1bDQKoaagwLWUmK/w8/EpnyOCI5sARjoxRZT3
            YCWtx2T9jYYZPisEDT7+/Jug2x4bop6zvV0AkSrOfgoTxOJWhXEFbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-07T11:57:07Z"
    mac: ENC[AES256_GCM,data:gGgMk/ZMVMsFHX7L3Z9KrYC+90aKj2P/yMKwCWc44JwIxOTYq7jYrMiJ/e/teSwoifXHnYcq65hxSjO/YRNdCcJOlLGr6rpjX+j77sd0A6GjooYKgyALnII8BV1J2tii4W+uS5fnnSj/wBT/esONTDiORXhfYl71BWs1DZhrVP8=,iv:I4Ev8b+w1ZLINUC6E23h8vwBpvyCN9f5jmslvESYkUE=,tag:mA9IujYha4zaht4qGLHH2g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
