# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [];

  boot.initrd.availableKernelModules = ["ata_piix" "uhci_hcd" "sr_mod" "xen_blkfront" "xen-blkfront" "xen-kbdfront"];
  boot.initrd.kernelModules = ["dm-snapshot"];
  boot.initrd.systemd.enable = true;

  boot.kernelModules = [];
  boot.extraModulePackages = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = false;
  networking.useNetworkd = true;
  networking.interfaces.enX0.ipv4.addresses = [
    {
      address = "209.209.9.184";
      prefixLength = 24;
    }
  ];
  networking.defaultGateway = {
    address = "209.209.9.1";
    interface = "enX0";
  };
  networking.nameservers = ["1.1.1.1" "1.0.0.1"];
  # networking.interfaces.enX0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
